.TH YAXWM 1 yaxwm\-VERSION
.SH NAME
yaxwm \- Yet another X window manager, as if we didn't have enough.
.SH SYNOPSIS
.B yaxwm
.RB [ \-v ]
.RB [ \-s
.RB SOCKET_FD]
.SH DESCRIPTION
.P
Yaxwm is a tiling window manager with inspiration from dwm, xmonad, and bspwm.
.P
Windows are managed in tiled, monocle, or floating layouts, and are grouped by
workspaces. Each window can be assigned to a single workspace and will have a
small border to indicate the focus state. Windows are arranged into pre-defined
layouts, a layout can be applied to workspaces and changes to one will
not impact the others.
.P
In tiled layout windows are organized in a master and two stack areas,
the number of masters and first stack windows can be adjusted
from 0-n with the second stack containing all remaining windows.
.P
In monocle layout windows are maximized and stacked on top of each other with
only one visible at a time.
.P
In floating layout windows are not organized or placed in any particular way
and can be moved or resized freely.
.SH OPTIONS
.TP
.B \-v
Prints version information to standard out and exits.
.TP
.B \-s
Use an existing socket connection file descriptor.
.SH USAGE
.SS COMMANDS
TODO - Somebody yell at me!
.SH CUSTOMIZATION
For basic changes yaxwm can be customized by running commands through yaxcmd.
On startup yaxwm looks for a yaxwmrc file in $HOME/.config/yaxwm and tries
to execute it. This file is just a shell script to run commands, it must be
executable.
.P
Further configuration such as adding layouts or callbacks can be done by
copying the default config header to config.h, editing it, and recompiling.
.SH BUGS
Please submit a bug report with as much detail as possible to
.B https://bitbucket.org/natemaia/yaxwm/issues/new
.SH AUTHORS/CONTRIBUTORS
Nathaniel Maia <\fInatemaia10@gmail.com\fR>, Dmitry Belitsky <\fIdmitry.belitsky@gmail.com\fR>
